services:
  weather-service:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # External API (only configurable env var)
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY:-}

      # AWS / LocalStack (hardcoded for Docker Compose)
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566

      # Cache config
      - CACHE_ENABLED=true
      - CACHE_BACKEND=redis
      - CACHE_TTL_SECONDS=300
      - CACHE_PREFIX=weather-cache
      - REDIS_URL=redis://redis:6379/0

      # Rate limiting config
      - RATE_LIMIT_ENABLED=false
      - RATE_LIMIT_REDIS_HOST=redis
      - RATE_LIMIT_REDIS_PORT=6379
      - RATE_LIMIT_REDIS_DB=0
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW_SECONDS=60

      # Data store config
      - DATA_STORE_TYPE=aws_s3
      - DATA_STORE_LOCAL_DIRECTORY=data
      - DATA_STORE_S3_BUCKET_NAME=weather-svc-data
      - DATA_STORE_S3_FOLDER_NAME=weather

      # Event store config
      - EVENT_STORE_TYPE=aws_dynamodb
      - EVENT_STORE_LOCAL_FILE_PATH=events.log
      - EVENT_STORE_AWS_DYNAMODB_TABLE_NAME=weather-svc-events

    depends_on:
      init-localstack:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - weather-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    networks:
      - weather-network

  init-localstack:
    image: amazon/aws-cli:latest
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DATA_STORE_S3_BUCKET_NAME=weather-svc-data
      - EVENT_STORE_AWS_DYNAMODB_TABLE_NAME=weather-svc-events
    volumes:
      - ./deployment/init-localstack.sh:/init-localstack.sh:ro
    entrypoint: ["/bin/bash", "/init-localstack.sh"]
    restart: "no"
    networks:
      - weather-network

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge

volumes:
  redis-data:
